<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_country</name>
   <tag></tag>
   <elementGuidId>f4173f10-4628-473c-b05a-380b217fa11e</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billCountry</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
ANTIGUA AND BARBUDA 
ALBANIA 
ALGERIA 
ANDORRA 
ASHMORE AND CARTIER ISLANDS 
AUSTRALIA 
AMERICAN SAMOA 

ARGENTINA 
AUSTRIA 
ANGUILLA 
BAHAMAS 
BAHRAIN 
BAKER ISLAND 
BANGLADESH 
BARBADOS 
BASSA DE INDIA 
BELGIUM 
BELIZE 
BENIN 
BERMUDA 
BHUTAN 
BOLIVIA 
BOSNIA AND HERZEGOVINA 
BOTSWANA 

BOUVET ISLAND 
BRAZIL 
BRITISH INDIAN OCEAN TERRITORY 
BRITISH VIRGIN ISLANDS 
BRUNEI 
BURMA 
BURUNDI 
CANADA 
CAPE VERDE 
CAYMAN ISLANDS 
CENTRAL AFRICAN REPUBLIC 
CHAD 
CHILE 
CHINA 
CHRISTMAS ISLAND 
CLIPPERTON ISLAND 
COCOS (KEELING) ISLANDS 

COLOMBIA 
COMOROS 
CONGO 
COOK ISLANDS 
CORAL SEA ISLANDS 
CROATIA 
CUBA 
CYPRUS 
CZECH REPUBLIC 
DENMARK 
DJIBOUTI 
DOMINICA 
DOMINICAN REPUBLIC 
ECUADOR 
EGYPT 
EL SALVADOR 
EQUATORIAL GUINEA 

ERITREA 
ETHIOPIA 
EUROPA ISLAND 
FAROE ISLANDS 
FIJI 
FINLAND 
FRANCE 
FRENCH GUIANA 
FRENCH POLYNESIA 
FRENCH SOUTHERN AND ANTARCTIC LANDS 
GABON 
GAZA STRIP 
GEORGIA 
GHANA 
GIBRALTAR 
GLORIOSO ISLANDS 
GREECE 

GREENLAND 
GRENADA 
GUADELOUPE 
GUAM 
GUATEMALA 
GUERNSEY 
GUINEA 
GUINEA-BISSAU 
GUYANA 
HAITI 
HEARD ISLAND AND MCDONALD ISLANDS 
HONDURAS 
HONG KONG 
HOWLAND ISLAND 
HUNGARY 
ICELAND 
INDIA 

INDONESIA 
IRELAND 
ISRAEL 
ITALY 
COTE D'IVOIRE 
JAMAICA 
JAN MAYEN 
JAPAN 
JARVIS ISLAND 
JERSEY 
JOHNSTON ATOLL 
JORDAN 
JUAN DE NOVA ISLAND 
CAMBODIA 
KENYA 
KINGMAN REEF 
KIRIBATI 

KUWAIT 
KYRGYZSTAN 
LAOS 
LATVIA 
LEBANON 
LESOTHO 
LIBERIA 
LIECHTENSTEIN 
LITHUANIA 
LUXEMBOURG 
MACAU 
MADAGASCAR 
MALAWI 
MALAYSIA 
MALDIVES 
MALI 
MALTA 

MAN, ISLE OF 
MARTINIQUE 
MAURITANIA 
MAURITIUS 
MAYOTTE 
MEXICO 
MIDWAY ISLANDS 
MOLDOVA 
MONACO 
MONGOLIA 
MONTENEGRO 
MONTSERRAT 
MOROCCO 
MOZAMBIQUE 
NAMIBIA 
NAURU 
NAVASSA ISLAND 

NEPAL 
NETHERLANDS 
NETHERLANDS ANTILLES 
NEW CALEDONIA 
NEW ZEALAND 
NICARAGUA 
NIGER 
NIGERIA 
NIUE 
NO MANS LAND 
NORFOLK ISLAND 
NORTHERN MARIANA ISLANDS 
NORWAY 
OMAN 
PALMYRA ATOLL 
PANAMA 
PAPUA NEW GUINEA 

PARACEL ISLANDS 
PARAGUAY 
PERU 
PHILIPPINES 
PITCAIRN ISLANDS 
POLAND 
PORTUGAL 
PUERTO RICO 
QATAR 
REUNION 
ROMANIA 
RWANDA 
ST. KITTS AND NEVIS 
ST. HELENA 
ST. LUCIA 
ST. PIERRE AND MIQUELON 
ST. VINCENT AND THE GRENADINES 

SAN MARINO 
SAO TOME AND PRINCIPE 
SENEGAL 
SERBIA 
SEYCHELLES 
SIERRA LEONE 
SINGAPORE 
SLOVAKIA 
SLOVENIA 
SOLOMON ISLANDS 
SOUTH AFRICA 
189
SPAIN 
SPRATLY ISLANDS 
SRI LANKA 
SUDAN 
SURINAME 

SVALBARD 
SWAZILAND 
SWEDEN 
SWITZERLAND 
SYRIA 
THAILAND 
TOGO 
TOKELAU 
TONGA 
TRINIDAD AND TOBAGO 
TROMELIN ISLAND 
TUNISIA 
TURKEY 
TURKS AND CAICOS ISLANDS 
TUVALU 
UGANDA 
SOVIET UNION 

UKRAINE 
UNITED ARAB EMIRATES 
UNITED KINGDOM 
UNITED STATES 
BURKINA FASO 
URUGUAY 
UZBEKISTAN 
VANUATU 
VATICAN CITY 
VENEZUELA 
VIRGIN ISLANDS 
WAKE ISLAND 
WALLIS AND FUTUNA 
WEST BANK 
WESTERN SAHARA 
WESTERN SAMOA 
ZAIRE 

ZAMBIA 
ZIMBABWE 
TAIWAN 
YUGOSLAVIA 
UNDERSEA FEATURES 
ANTARCTICA 
BULGARIA 
ARUBA 
FALKLAND ISLANDS 
OCEANS 
COSTA RICA 
YEMEN 
BELARUS 
GERMANY 
ARMENIA 
KAZAKHSTAN 
TAJIKISTAN 

TURKMENISTAN 
ESTONIA 
AFGHANISTAN 
AZERBAIJAN 
PAKISTAN 
ANGOLA 
VIETNAM 
CAMEROON 
IRAN 
IRAQ 
RUSSIA 
SAUDI ARABIA 
LIBYA 
KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF 
KOREA, REPUBLIC OF 
TANZANIA, UNITED REPUBLIC OF 
GAMBIA, THE 

SOMALIA 
MACEDONIA, FORMER REPUBLIC OF 
MARSHALL ISLANDS 
MICRONESIA 
</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[1]/table[1]/tbody[1]/tr[1]/td[2]/table[1]/tbody[1]/tr[4]/td[1]/table[1]/tbody[1]/tr[1]/td[2]/table[1]/tbody[1]/tr[5]/td[1]/form[1]/table[1]/tbody[1]/tr[13]/td[2]/select[1]</value>
   </webElementProperties>
</WebElementEntity>
